#!/usr/bin/env bash
# Wrapper generated by repo-onboard: invokes this repository's canonical
# check command (`pytest`), preferring a repo virtualenv over PATH.
set -uo pipefail

script_directory="${BASH_SOURCE[0]%/*}"
repository_root="$(cd "$script_directory/.." && pwd -P)"
cd "$repository_root"

resolve_tool() {
  local tool="$1"
  local candidate
  for candidate in ".venv/bin/$tool" "venv/bin/$tool"; do
    if [[ -x "$candidate" && ! -d "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  command -v "$tool" 2>/dev/null
}

resolved_command=(pytest )
tool_bin="$(resolve_tool "${resolved_command[0]}")"
if [[ -z "$tool_bin" ]]; then
  printf 'not ok - %s (tool unavailable)\n' "${resolved_command[0]}" >&2
  exit 1
fi
exec "$tool_bin" "${resolved_command[@]:1}"
